-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.complement_main_dish
(
    id_main_dish bigint NOT NULL,
    id_side_dish bigint NOT NULL,
    CONSTRAINT complement_main_dish_pkey PRIMARY KEY (id_main_dish, id_side_dish)
);

CREATE TABLE IF NOT EXISTS public.ingredient
(
    id_ingredient bigserial NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT ingredient_pkey PRIMARY KEY (id_ingredient)
);

CREATE TABLE IF NOT EXISTS public.ingredients_poke
(
    id_ingredient bigint NOT NULL,
    id_poke bigint NOT NULL,
    CONSTRAINT ingredients_poke_pkey PRIMARY KEY (id_ingredient, id_poke)
);

CREATE TABLE IF NOT EXISTS public.maindish
(
    id_maindish bigserial NOT NULL,
    menu_id_menu bigint,
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT maindish_pkey PRIMARY KEY (id_maindish)
);

CREATE TABLE IF NOT EXISTS public.menu
(
    price double precision,
    id_menu bigserial NOT NULL,
    "day of week" character varying(255) COLLATE pg_catalog."default",
    drink character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT menu_pkey PRIMARY KEY (id_menu)
);

CREATE TABLE IF NOT EXISTS public.poke
(
    id_poke bigserial NOT NULL,
    menu_id_menu bigint,
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT poke_pkey PRIMARY KEY (id_poke)
);

CREATE TABLE IF NOT EXISTS public.side_dish
(
    id_side_dish bigserial NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT side_dish_pkey PRIMARY KEY (id_side_dish)
);

ALTER TABLE IF EXISTS public.complement_main_dish
    ADD CONSTRAINT fk82383746pevcaut8c08vglxjx FOREIGN KEY (id_main_dish)
    REFERENCES public.maindish (id_maindish) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.complement_main_dish
    ADD CONSTRAINT fkq6xbvxqhb08dn3dsifqcoum8q FOREIGN KEY (id_side_dish)
    REFERENCES public.side_dish (id_side_dish) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ingredients_poke
    ADD CONSTRAINT fk9boirfhv6du5mxlksnd55meex FOREIGN KEY (id_poke)
    REFERENCES public.poke (id_poke) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ingredients_poke
    ADD CONSTRAINT fkli92u6kl6ljy10jbinps9y2iq FOREIGN KEY (id_ingredient)
    REFERENCES public.ingredient (id_ingredient) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.maindish
    ADD CONSTRAINT fk7b3gswujffnpcccpyw9llf3ot FOREIGN KEY (menu_id_menu)
    REFERENCES public.menu (id_menu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.poke
    ADD CONSTRAINT fkoo43w9j6qb9p6nyumsfpnhcws FOREIGN KEY (menu_id_menu)
    REFERENCES public.menu (id_menu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;