version: "3.8"
services:

    db:
        image: bitnami/postgresql:16.2.0
        environment:
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_DB=restaurant
            - POSTGRES_PASSWORD=toor
            - POSTGRES_USER=root

        volumes:
            # Utilizar la ruta
            - db-dat:/bitnami/postgresql
        ports:
            - "5342:5432"
    pgadmin:
        image: dpage/pgadmin4:8.4
        depends_on:
            - db
        ports:
            - "80:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin

volumes:
    db-dat:
