version: '3.8'
services:
    pgdatabase:
        image: postgres:13
        container_name: coffeeshop-postgresdb
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=pasword
            - POSTGRES_DB=coffeeshop
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - "8080:80"